### ISSUE TITLE
Tunning checkstyle outside of Gradle

### ISSUE THREAD

**Issue by aerostitch** [navit-gps/navit#945]
So after realizing that @jandegr probably meant why even use gradle to run checkstyle (that would actually save the time of the initialization of Gradle so also related to #910 ) in that specific check in his comment here: https://github.com/navit-gps/navit/pull/936#issuecomment-549036698 I tried to run checkstyle from the Debian package itself and get an error:
```
$ checkstyle -c checkstyle.xml ./navit/android/src/org/navitproject/navit/NavitAppConfig.java
log4j:WARN No appenders could be found for logger (com.puppycrawl.tools.checkstyle.Main).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - TreeWalker is not allowed as a parent of LineLength Please review 'Parent Module' section for this Check in web documentation if Check is stan
dard.
        at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:472)
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:198)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:398)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:326)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:187)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:124)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: TreeWalker is not allowed as a parent of LineLength Please review 'Parent Module' section for this Check in web documentation if Check is standard.
        at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:147)
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:198)
        at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:467)
        ... 5 more
Checkstyle ends with 1 errors.
```

I'm going to dig a bit more as to why it works perfectly with gradle and not without.
@metalstrolch is the error that you have on Gentoo the same? (cf. https://github.com/navit-gps/navit/pull/944#issuecomment-551664037)

(Mostly creating the issue to make sure that not 2 people work on that at the same time)

**Comment by metalstrolch** [comment]
@aerostitch No, not exactly. It gave me the following :
```
checkstyle -c checkstyle.xml ./navit/android/src/org/navitproject/navit/NavitAppConfig.java
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - Token "METHOD_REF" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.whitespace.SeparatorWrapCheck
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:432)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:137)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:420)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:358)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:173)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Token "METHOD_REF" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.whitespace.SeparatorWrapCheck
	at com.puppycrawl.tools.checkstyle.TreeWalker.registerCheck(TreeWalker.java:225)
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:162)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:137)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:427)
	... 4 more
Checkstyle ends with 1 errors.

```
Of course this may still be a version issue. The METHOD_REF token was added to checkstyle in 2016, at least according to https://github.com/checkstyle/checkstyle
The version Gentoo has is:
```
emerge -pv checkstyle

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild   R    ] dev-util/checkstyle-7.2::gentoo  USE="-doc -source" 0 KiB

Total: 1 package (1 reinstall), Size of downloads: 0 KiB

```
Lates availale seems to be 8.26
